/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanilhaRouteImport } from './routes/planilha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPaypalCreateOrderRouteImport } from './routes/api/public/paypal-create-order'
import { Route as ApiPublicPaypalCaptureOrderRouteImport } from './routes/api/public/paypal-capture-order'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicDownloadLeadsRouteImport } from './routes/api/public/download-leads'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'

const PlanilhaRoute = PlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaypalCreateOrderRoute =
  ApiPublicPaypalCreateOrderRouteImport.update({
    id: '/api/public/paypal-create-order',
    path: '/api/public/paypal-create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalCaptureOrderRoute =
  ApiPublicPaypalCaptureOrderRouteImport.update({
    id: '/api/public/paypal-capture-order',
    path: '/api/public/paypal-capture-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadLeadsRoute = ApiPublicDownloadLeadsRouteImport.update({
  id: '/api/public/download-leads',
  path: '/api/public/download-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planilha': typeof PlanilhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/download-leads': typeof ApiPublicDownloadLeadsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/paypal-capture-order': typeof ApiPublicPaypalCaptureOrderRoute
  '/api/public/paypal-create-order': typeof ApiPublicPaypalCreateOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planilha': typeof PlanilhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/download-leads': typeof ApiPublicDownloadLeadsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/paypal-capture-order': typeof ApiPublicPaypalCaptureOrderRoute
  '/api/public/paypal-create-order': typeof ApiPublicPaypalCreateOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/planilha': typeof PlanilhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/api/public/download-leads': typeof ApiPublicDownloadLeadsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/paypal-capture-order': typeof ApiPublicPaypalCaptureOrderRoute
  '/api/public/paypal-create-order': typeof ApiPublicPaypalCreateOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planilha'
    | '/admin'
    | '/clientes'
    | '/api/public/bookings'
    | '/api/public/download-leads'
    | '/api/public/leads'
    | '/api/public/paypal-capture-order'
    | '/api/public/paypal-create-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planilha'
    | '/admin'
    | '/clientes'
    | '/api/public/bookings'
    | '/api/public/download-leads'
    | '/api/public/leads'
    | '/api/public/paypal-capture-order'
    | '/api/public/paypal-create-order'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planilha'
    | '/_authenticated/admin'
    | '/_authenticated/clientes'
    | '/api/public/bookings'
    | '/api/public/download-leads'
    | '/api/public/leads'
    | '/api/public/paypal-capture-order'
    | '/api/public/paypal-create-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanilhaRoute: typeof PlanilhaRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  ApiPublicDownloadLeadsRoute: typeof ApiPublicDownloadLeadsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicPaypalCaptureOrderRoute: typeof ApiPublicPaypalCaptureOrderRoute
  ApiPublicPaypalCreateOrderRoute: typeof ApiPublicPaypalCreateOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planilha': {
      id: '/planilha'
      path: '/planilha'
      fullPath: '/planilha'
      preLoaderRoute: typeof PlanilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paypal-create-order': {
      id: '/api/public/paypal-create-order'
      path: '/api/public/paypal-create-order'
      fullPath: '/api/public/paypal-create-order'
      preLoaderRoute: typeof ApiPublicPaypalCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-capture-order': {
      id: '/api/public/paypal-capture-order'
      path: '/api/public/paypal-capture-order'
      fullPath: '/api/public/paypal-capture-order'
      preLoaderRoute: typeof ApiPublicPaypalCaptureOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-leads': {
      id: '/api/public/download-leads'
      path: '/api/public/download-leads'
      fullPath: '/api/public/download-leads'
      preLoaderRoute: typeof ApiPublicDownloadLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanilhaRoute: PlanilhaRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  ApiPublicDownloadLeadsRoute: ApiPublicDownloadLeadsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicPaypalCaptureOrderRoute: ApiPublicPaypalCaptureOrderRoute,
  ApiPublicPaypalCreateOrderRoute: ApiPublicPaypalCreateOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
